sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t rs059/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rs059/docker-react npm run test -- --coverage