sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t rs059/docker-react .

script:
  - 'bundle exec rake spec'
  - docker run -e CI=true rs059/docker-react npm run test -- --coverage